apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.port }}
      {{- if .Values.kibana.service.nodePort }}
      nodePort: {{ .Values.kibana.service.nodePort }}
      {{- end }}
