replicaCount: 1

#service:
#  type: ClusterIP
#  port: 8080
#  targetPort: 8080

flightService:
  image:
    repository: flightservices-flight-service
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 2
  service:
    type: NodePort
    port: 8080
    nodePort: 30080

mysql:
  host: mysql
  image: mysql:8.0
  database: flightdb
  username: flightuser
  password: flightpass
  rootPassword: rootpass
  service:
    port: 3306

# Elasticsearch / Logstash config
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
  port: 9200
  resources:
    limits:
      memory: 512Mi
      cpu: 0.5
    requests:
      memory: 256Mi
      cpu: 0.25
  enabled: true

# Kibana config
kibana:
  image: docker.elastic.co/kibana/kibana:7.17.17
  service:
    type: NodePort
    port: 5601
    nodePort: 30601
  enabled: true

# Logstash
logstash:
  image: docker.elastic.co/logstash/logstash:7.17.17
  service:
    port: 5000
  enabled: true